version: '2'
services:
  modbus2-app:
    image: modbus2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://modbus2-mssql:1433;database=modbus2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  modbus2-mssql:
    extends:
      file: mssql.yml
      service: modbus2-mssql
